name: Say Good Bye

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  good-bye:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        
      - name: Goodbye Sautet
        run: echo "Byee sautet"
        shell: bash
      
