name: Test work flow

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
      - run: echo "Hello sautet"
        shell: bash
  
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye
      - run: echo "Goodbye sautet"
        shell: bash

   
