name: Test Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
  
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Hello world
        run: echo "Hello sautet"
        shell: bash
